### ISSUE TITLE
FormatterExtensions.jsonSerializer keeps wrong serializer with Diagnostics

### ISSUE THREAD

**Issue by xmedeko** [NancyFx/Nancy.Serialization.JsonNet#37] opened 2016-04-06 09:04 UTC
I have Nancy 1.4.3, Nancy.Serialization.JsonNet 1.4.1. When start my app with Nancy diagnostics and go first to the `http://localhost:8080/_Nancy/interactive#Testing%20Diagnostic%20Provider` and then run my request, the request is formatted by the `DefaultJsonSerializer` and not `JsonNetSerializer` since the `FormatterExtensions.jsonSerializer` keeps the `DefaultJsonSerializer` from the first request.

I guess both `jsonSerializer` and `xmlSerializer` fields should be removed.

**Comment by khellang** [comment] 2016-04-06 09:09
Isn't this a duplicate of #36?

**Closed** 2016-04-06 09:09 UTC

**Comment by xmedeko** [comment] 2016-04-06 09:37
No it's not a duplicate. These are two different problems.

**Comment by khellang** [comment] 2016-04-06 09:45
How are these two different problems? By your description it seems to be exactly the same. It's picking the wrong serializer?

**Comment by xmedeko** [comment] 2016-04-06 09:48
The #36 is that the `formatter.Serializer` has different order depending on the machine/environment.
This bug is about wrong caching of `FormatterExtensions.jsonSerializer` on the same machine/environment.

**Comment by khellang** [comment] 2016-04-06 10:00
"wrong caching"? I'm very confused :confused:

**Comment by xmedeko** [comment] 2016-04-06 10:03
Look at the FormatterExtensions.AsJson code:
```c#
var serializer = jsonSerializer ?? (jsonSerializer = formatter.Serializers.FirstOrDefault(s => s.CanSerialize("application/json")));
```
It takes the first JSON serializer from the formatter from the first call and caches it in the `jsonSerializer`. So, when the next call has different formatters, it still uses the one from `jsonSerializer`.

**Comment by khellang** [comment] 2016-04-06 10:07
How can the next call have "different formatters"? The container configuration is set up once. It won't change at runtime.

**Comment by xmedeko** [comment] 2016-04-06 13:19
Ask the Nancy Diagnostics author. It's either a bug of the `FormatterExtensions.jsonSerializer` or the `Nancy.Diagnostics`.

_Note:_ IMO `FormatterExtensions.AsJson` has the `IResponseFormatter` parameter and should work well with all `IResponseFormatter` objects, even if I create my own `IResponseFormatter` independent of the container configuration.

**Comment by khellang** [comment] 2016-04-06 13:24
> Ask the Nancy Diagnostics author. It's either a bug of the FormatterExtensions.jsonSerializer or the Nancy.Diagnostics.

Either way, this issue has nothing to do with the Newtonsoft.Json serializer :smile:

**Comment by xmedeko** [comment] 2016-04-06 13:31
OK, created https://github.com/NancyFx/Nancy/issues/2399
